.ifndef RESOURCES_INC
RESOURCES_INC = 1

tilefilename: .literal "TILES.BIN"
end_tilefilename:

tilemapfilename: .literal "L0MAP.BIN"
end_tilemapfilename:

tilemap2filename: .literal "L1MAP.BIN"
end_tilemap2filename:

spritefile: .literal "SPRITES.BIN"	
end_spritefile:

aurorafile: .literal "AURORA.BIN"	
end_aurorafile:

collisionfile: .literal "CLSN.BIN"
end_collisionfile:

collisionmapfile: .literal "CLSNMAP.BIN"
end_collisionmapfile:

.endif ; RESOURCES_INC
