.ifndef RESOURCES_INC
RESOURCES_INC = 1

titlefile: .literal "TITLE.BIN"
end_titlefile:

titlepalfile: .literal "TIPAL.BIN"
end_titlepalfile:

title_music_file: .literal "TITLE.ZSM"
end_title_music_file:

vimaskfile: .literal "VIMASK.BIN"
end_vimaskfile:

spritefile: .literal "SPRITES.BIN"	
end_spritefile:

aurorafile: .literal "AURORA.BIN"	
end_aurorafile:

lunafile: .literal "LUNA.BIN"
end_lunafile:

connorfile: .literal "CONNOR.BIN"
end_connorfile:

georgefile: .literal "GEORGE.BIN"
end_georgefile:

elliotfile: .literal "ELLIOT.BIN"
end_elliotfile:

olliefile: .literal "OLLIE.BIN"
end_olliefile:

collisionfile: .literal "CLSN.BIN"
end_collisionfile:

charsetfile: .literal "CHARSET.BIN"
end_charsetfile:


.endif ; RESOURCES_INC
