.ifndef RESOURCES_INC
RESOURCES_INC = 1

spritefile: .literal "SPRITES.BIN"	
end_spritefile:

aurorafile: .literal "AURORA.BIN"	
end_aurorafile:

lunafile: .literal "LUNA.BIN"
end_lunafile:

connorfile: .literal "CONNOR.BIN"
end_connorfile:

collisionfile: .literal "CLSN.BIN"
end_collisionfile:

charsetfile: .literal "CHARSET.BIN"
end_charsetfile:

pixryn_tile_file: .literal "PITILES.BIN"
end_pixryn_tile_file:

pixryn_l0_map_file: .literal "PIL0MAP.BIN"
end_pixryn_l0_map_file:

pixryn_l1_map_file: .literal "PIL1MAP.BIN"
end_pixryn_l1_map_file:

pixryn_collision_map_file: .literal "PICLSNMAP.BIN"
end_pixryn_collision_map_file:

pixryn_interaction_map_file: .literal "PIINT.BIN"
end_pixryn_interaction_map_file:

interior_tile_file: .literal "INTERIOR.BIN"
end_interior_tile_file:

tavern_l0_map_file: .literal "TAVL0.BIN"
end_tavern_l0_map_file:

tavern_l1_map_file: .literal "TAVL1.BIN"
end_tavern_l1_map_file:

tavern_collision_map_file: .literal "TAVCLSN.BIN"
end_tavern_collision_map_file:

pixryn_tavern_interaction_map_file: .literal "PITAVINT.BIN"
end_pixryn_tavern_interaction_map_file:

.endif ; RESOURCES_INC
