.ifndef AKOKO_RESOURCES_INC
AKOKO_RESOURCES_INC = 1

; Akoko Shared Resources
akoko_tile_file: .literal "AMTILES.BIN"
end_akoko_tile_file:

akoko_pal_file: .literal "AMPAL.BIN"
end_akoko_pal_file:

; Akoko Overworld Resources
akoko_l0_map_file: .literal "AML0MAP.BIN"
end_akoko_l0_map_file:

akoko_l1_map_file: .literal "AML1MAP.BIN"
end_akoko_l1_map_file:

akoko_collision_map_file: .literal "AMCLSNMAP.BIN"
end_akoko_collision_map_file:

akoko_interaction_map_file: .literal "AMINT.BIN"
end_akoko_interaction_map_file:

akoko_message_file: .literal "AMMSG.BIN"
end_akoko_message_file:

.endif ; AKOKO_RESOURCES_INC
